<?php
namespace App\Http\Controllers\Api;

use App\Models\AuditLog;
use App\Models\Customer;
use App\Models\Equipment;
use App\Models\InventoryMovement;
use App\Models\NotificationTemplate;
use App\Models\Product;
use App\Models\Quote;
use App\Models\QuoteItem;
use App\Models\Receivable;
use App\Models\RoutePlan;
use App\Models\RouteStop;
use App\Models\Service;
use App\Models\TimeEntry;
use App\Models\Vehicle;
use App\Models\WorkOrder;
use App\Models\WorkOrderProduct;
use App\Models\WorkOrderService;
use App\Models\WorkOrderStatusHistory;
use App\Services\AuditService;
use App\Services\ReceivableService;
use App\Services\InventoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OperationsController {
    public function inventory(Request $r){return InventoryMovement::with('product')->latest('occurred_at')->paginate(100);}
    public function adjustStock(Request $r,Product $product,AuditService $audit){$data=$r->validate(['quantity'=>'required|numeric|not_in:0','type'=>'required|in:entry,exit,adjustment','reason'=>'required|string|max:255']);return DB::transaction(function()use($product,$data,$audit){$old=(float)$product->stock;$quantity=$data['type']==='exit'?-abs((float)$data['quantity']):($data['type']==='entry'?abs((float)$data['quantity']):(float)$data['quantity']);$new=$old+$quantity;if($new<0)abort(422,'Estoque insuficiente para esta saída.');$product->update(['stock'=>$new]);$move=InventoryMovement::create(['product_id'=>$product->id,'user_id'=>auth()->id(),'type'=>$data['type'],'quantity'=>$quantity,'balance_after'=>$new,'reason'=>$data['reason'],'occurred_at'=>now()]);$audit->record('inventory_adjusted',$product,['stock'=>$old],['stock'=>$new],$data['reason']);return response()->json(['data'=>$move->load('product')],201);});}
    public function receivables(ReceivableService $sync){WorkOrder::with('payments')->get()->each(fn($order)=>$sync->sync($order));return Receivable::with(['customer','workOrder'])->orderBy('due_date')->paginate(100);}
    public function reports(Request $r){$from=$r->input('from',now()->startOfMonth()->toDateString());$to=$r->input('to',now()->toDateString());$orders=WorkOrder::with(['technician','services','products','payments'])->whereBetween('scheduled_at',[$from.' 00:00:00',$to.' 23:59:59'])->get();return response()->json(['data'=>['period'=>compact('from','to'),'revenue'=>(float)$orders->flatMap->payments->sum('amount'),'orders'=>$orders->count(),'completed'=>$orders->where('status','completed')->count(),'by_service'=>$orders->flatMap->services->groupBy('name')->map(fn($items)=>['quantity'=>(float)$items->sum('quantity'),'total'=>(float)$items->sum('total')])->all(),'by_technician'=>$orders->groupBy('technician.name')->map(fn($items)=>['orders'=>$items->count(),'revenue'=>(float)$items->flatMap->payments->sum('amount')])->all(),'low_stock'=>Product::whereColumn('stock','<=','minimum_stock')->get(['id','name','stock','minimum_stock'])]]);}
    public function timeEntries(Request $r){return TimeEntry::with('employee.user')->when($r->employee_id,fn($q,$v)=>$q->where('employee_id',$v))->when($r->date,fn($q,$v)=>$q->whereDate('work_date',$v))->orderByDesc('occurred_at')->paginate(200);}
    public function adjustTime(Request $r,TimeEntry $entry,AuditService $audit){$data=$r->validate(['occurred_at'=>'required|date','reason'=>'required|string|max:255']);$old=$entry->occurred_at;$entry->update(['occurred_at'=>$data['occurred_at'],'adjusted'=>true,'notes'=>trim(($entry->notes?' '.$entry->notes:'').' Ajuste: '.$data['reason'])]);$audit->record('time_entry_adjusted',$entry,['occurred_at'=>$old],['occurred_at'=>$entry->occurred_at],$data['reason']);return response()->json(['data'=>$entry]);}
    public function preventive(){return Equipment::with(['customer','address'])->whereNotNull('next_maintenance_at')->whereDate('next_maintenance_at','<=',now()->addDays(60))->orderBy('next_maintenance_at')->paginate(100);}
    public function vehicles(){return Vehicle::orderBy('license_plate')->paginate(100);}
    public function storeVehicle(Request $r){return response()->json(['data'=>Vehicle::create($this->vehicleRules($r))],201);}
    public function updateVehicle(Request $r,Vehicle $vehicle){$vehicle->update($this->vehicleRules($r,false));return response()->json(['data'=>$vehicle]);}
    public function deleteVehicle(Vehicle $vehicle){$vehicle->delete();return response()->noContent();}
    private function vehicleRules(Request $r,bool $required=true):array{return $r->validate(['license_plate'=>($required?'required':'sometimes').'|string|max:15|unique:vehicles,license_plate,'.($r->route('vehicle')?->id??''),'model'=>($required?'required':'sometimes').'|string|max:100','brand'=>'nullable|string|max:80','year'=>'nullable|integer|min:1950|max:2100','mileage'=>'nullable|integer|min:0','active'=>'sometimes|boolean']);}
    public function routes(){return RoutePlan::with(['technician','vehicle','stops.appointment.customer','stops.workOrder.customer'])->orderByDesc('route_date')->paginate(100);}
    public function storeRoute(Request $r){$data=$r->validate(['technician_id'=>'nullable|exists:employees,id','vehicle_id'=>'nullable|exists:vehicles,id','route_date'=>'required|date','notes'=>'nullable|string','stops'=>'array','stops.*.appointment_id'=>'nullable|exists:appointments,id','stops.*.work_order_id'=>'nullable|exists:work_orders,id','stops.*.planned_at'=>'nullable|date']);$stops=$data['stops']??[];unset($data['stops']);$route=DB::transaction(function()use($data,$stops){$route=RoutePlan::create($data);foreach($stops as $position=>$stop)RouteStop::create([...$stop,'route_id'=>$route->id,'position'=>$position+1]);return $route;});return response()->json(['data'=>$route->load(['technician','vehicle','stops.appointment.customer','stops.workOrder.customer'])],201);}
    public function updateRoute(Request $r,RoutePlan $route){$data=$r->validate(['technician_id'=>'nullable|exists:employees,id','vehicle_id'=>'nullable|exists:vehicles,id','route_date'=>'sometimes|date','status'=>'sometimes|in:planned,in_progress,completed','notes'=>'nullable|string','stops'=>'array','stops.*.appointment_id'=>'nullable|exists:appointments,id','stops.*.work_order_id'=>'nullable|exists:work_orders,id','stops.*.planned_at'=>'nullable|date']);$stops=$data['stops']??null;unset($data['stops']);$route->update($data);if($stops!==null){$route->stops()->delete();foreach($stops as $position=>$stop)RouteStop::create([...$stop,'route_id'=>$route->id,'position'=>$position+1]);}return response()->json(['data'=>$route->fresh()->load(['technician','vehicle','stops.appointment.customer','stops.workOrder.customer'])]);}
    public function destroyRoute(RoutePlan $route){$route->delete();return response()->noContent();}
    public function quotes(){return Quote::with(['customer','address','items'])->latest()->paginate(100);}
    public function storeQuote(Request $r){$data=$r->validate(['customer_id'=>'required|exists:customers,id','address_id'=>'nullable|exists:customer_addresses,id','valid_until'=>'nullable|date','notes'=>'nullable|string','discount'=>'nullable|numeric|min:0','items'=>'required|array|min:1','items.*.type'=>'required|in:service,product','items.*.service_id'=>'nullable|exists:services,id','items.*.product_id'=>'nullable|exists:products,id','items.*.quantity'=>'required|numeric|min:.001','items.*.unit_price'=>'required|numeric|min:0','items.*.discount'=>'nullable|numeric|min:0']);$quote=$this->saveQuote($data);return response()->json(['data'=>$quote],201);}
    public function updateQuote(Request $r,Quote $quote){$data=$r->validate(['valid_until'=>'nullable|date','notes'=>'nullable|string','discount'=>'nullable|numeric|min:0','status'=>'sometimes|in:awaiting_approval,approved,rejected,converted','items'=>'sometimes|array|min:1','items.*.type'=>'required|in:service,product','items.*.service_id'=>'nullable|exists:services,id','items.*.product_id'=>'nullable|exists:products,id','items.*.quantity'=>'required|numeric|min:.001','items.*.unit_price'=>'required|numeric|min:0','items.*.discount'=>'nullable|numeric|min:0']);if(isset($data['items'])){$items=$data['items'];unset($data['items']);$quote->update($data);$quote->items()->delete();return response()->json(['data'=>$this->attachQuoteItems($quote,$items)]);} $quote->update($data);return response()->json(['data'=>$quote->load(['customer','address','items'])]);}
    private function saveQuote(array $data):Quote{$items=$data['items'];unset($data['items']);return DB::transaction(function()use($data,$items){$quote=Quote::create([...$data,'number'=>'ORC-'.now()->format('Ym').'-'.str_pad((string)((Quote::withTrashed()->max('id')??0)+1),4,'0',STR_PAD_LEFT),'discount'=>$data['discount']??0]);return $this->attachQuoteItems($quote,$items);});}
    private function attachQuoteItems(Quote $quote,array $items):Quote{$subtotal=0;foreach($items as $item){$source=$item['type']==='service'?Service::find($item['service_id']):Product::find($item['product_id']);$discount=(float)($item['discount']??0);$total=max(0,(float)$item['quantity']*(float)$item['unit_price']-$discount);QuoteItem::create([...$item,'quote_id'=>$quote->id,'name'=>$source?->name??'Item','discount'=>$discount,'total'=>$total]);$subtotal+=$total;}$quote->update(['total'=>max(0,$subtotal-(float)$quote->discount)]);return $quote->fresh()->load(['customer','address','items']);}
    public function convertQuote(Quote $quote,ReceivableService $receivables,InventoryService $inventory){if($quote->status!=='approved')abort(422,'Apenas orçamentos aprovados podem ser convertidos.');$order=DB::transaction(function()use($quote,$inventory){$order=WorkOrder::create(['number'=>'OS-'.now()->format('Ym').'-'.str_pad((string)((WorkOrder::withTrashed()->max('id')??0)+1),4,'0',STR_PAD_LEFT),'customer_id'=>$quote->customer_id,'address_id'=>$quote->address_id,'quote_id'=>$quote->id,'scheduled_at'=>now(),'status'=>'scheduled','discount'=>$quote->discount,'notes'=>$quote->notes]);foreach($quote->items as $item){if($item->type==='service')WorkOrderService::create(['work_order_id'=>$order->id,'service_id'=>$item->service_id,'name'=>$item->name,'quantity'=>$item->quantity,'unit_price'=>$item->unit_price,'discount'=>$item->discount,'total'=>$item->total]);else {$product=Product::findOrFail($item->product_id);$inventory->consume($product,(float)$item->quantity,$order);WorkOrderProduct::create(['work_order_id'=>$order->id,'product_id'=>$item->product_id,'name'=>$item->name,'quantity'=>$item->quantity,'unit_price'=>$item->unit_price,'discount'=>$item->discount,'total'=>$item->total]);}}$order->update(['subtotal'=>$quote->items->sum('total'),'total'=>$quote->total]);$quote->update(['status'=>'converted']);WorkOrderStatusHistory::create(['work_order_id'=>$order->id,'user_id'=>auth()->id(),'to_status'=>'scheduled','occurred_at'=>now(),'notes'=>'Convertida do orçamento '.$quote->number]);return $order;});$receivables->sync($order);return response()->json(['data'=>$order->load(['customer','address','services','products','statusHistory'])],201);}
    public function templates(){return NotificationTemplate::orderBy('name')->paginate(100);}
    public function storeTemplate(Request $r){return response()->json(['data'=>NotificationTemplate::create($r->validate(['key'=>'required|string|max:80|unique:notification_templates,key','name'=>'required|string|max:120','channel'=>'required|string|max:30','body'=>'required|string','active'=>'sometimes|boolean']))],201);}
    public function updateTemplate(Request $r,NotificationTemplate $template){$template->update($r->validate(['key'=>'sometimes|required|string|max:80|unique:notification_templates,key,'.$template->id,'name'=>'sometimes|required|string|max:120','channel'=>'sometimes|required|string|max:30','body'=>'sometimes|required|string','active'=>'sometimes|boolean']));return response()->json(['data'=>$template]);}
    public function audit(){return AuditLog::with('user')->latest()->paginate(150);}
}
