<?php

use App\Http\Controllers\Api\AppointmentController;
use App\Http\Controllers\Api\AttachmentController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BusinessDocumentController;
use App\Http\Controllers\Api\CatalogController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\EmployeeController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\ReferenceDataController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\SettingsController;
use App\Http\Controllers\Api\TechnicianController;
use App\Http\Controllers\Api\TimeEntryController;
use App\Http\Controllers\Api\WorkOrderController;
use App\Http\Controllers\Api\WorkOrderTransitionController;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login']);
Route::middleware('auth.api')->group(function () {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('dashboard', DashboardController::class)->middleware('role:admin');
    Route::get('appointments', [AppointmentController::class, 'index']);
    Route::get('services', [ReferenceDataController::class, 'services']);
    Route::get('products', [ReferenceDataController::class, 'products']);
    Route::apiResource('work-orders', WorkOrderController::class)->parameters(['work-orders'=>'workOrder'])->only(['index','show','store','update']);
    Route::post('work-orders/{workOrder}/transition', WorkOrderTransitionController::class);
    Route::post('work-orders/{workOrder}/services', [WorkOrderController::class, 'addService']);
    Route::post('work-orders/{workOrder}/products', [WorkOrderController::class, 'addProduct']);
    Route::post('work-orders/{workOrder}/payments', [PaymentController::class, 'store']);
    Route::post('work-orders/{workOrder}/attachments', [AttachmentController::class, 'store']);
    Route::get('technician/today', [TechnicianController::class, 'today']);
    Route::post('time-entries/clock', [TimeEntryController::class, 'clock']);
    Route::middleware('role:admin')->group(function () {
        Route::delete('work-orders/{workOrder}', [WorkOrderController::class, 'destroy']);
        Route::apiResource('customers', CustomerController::class);
        Route::get('customers/{customer}/addresses', [ReferenceDataController::class, 'addresses']);
        Route::post('customers/{customer}/addresses', [ReferenceDataController::class, 'storeAddress']);
        Route::put('addresses/{address}', [ReferenceDataController::class, 'updateAddress']);
        Route::delete('addresses/{address}', [ReferenceDataController::class, 'destroyAddress']);
        Route::get('equipment', [ReferenceDataController::class, 'equipment']);
        Route::post('equipment', [ReferenceDataController::class, 'storeEquipment']);
        Route::get('equipment/{equipment}', [ReferenceDataController::class, 'showEquipment']);
        Route::put('equipment/{equipment}', [ReferenceDataController::class, 'updateEquipment']);
        Route::delete('equipment/{equipment}', [ReferenceDataController::class, 'destroyEquipment']);
        Route::get('employees', [ReferenceDataController::class, 'employees']);
        Route::post('employees', [ReferenceDataController::class, 'storeEmployee']);
        Route::put('employees/{employee}', [ReferenceDataController::class, 'updateEmployee']);
        Route::delete('employees/{employee}', [ReferenceDataController::class, 'destroyEmployee']);
        Route::apiResource('appointments', AppointmentController::class)->except(['index','show']);
        Route::post('services', [ReferenceDataController::class, 'storeService']);
        Route::put('services/{service}', [ReferenceDataController::class, 'updateService']);
        Route::delete('services/{service}', [ReferenceDataController::class, 'destroyService']);
        Route::post('products', [ReferenceDataController::class, 'storeProduct']);
        Route::put('products/{product}', [ReferenceDataController::class, 'updateProduct']);
        Route::delete('products/{product}', [ReferenceDataController::class, 'destroyProduct']);
        Route::get('inventory-movements', [OperationsController::class, 'inventory']);
        Route::post('products/{product}/stock-adjustment', [OperationsController::class, 'adjustStock']);
        Route::get('receivables', [OperationsController::class, 'receivables']);
        Route::get('reports', [OperationsController::class, 'reports']);
        Route::get('time-entries', [OperationsController::class, 'timeEntries']);
        Route::put('time-entries/{entry}/adjust', [OperationsController::class, 'adjustTime']);
        Route::get('preventive-maintenance', [OperationsController::class, 'preventive']);
        Route::get('vehicles', [OperationsController::class, 'vehicles']);
        Route::post('vehicles', [OperationsController::class, 'storeVehicle']);
        Route::put('vehicles/{vehicle}', [OperationsController::class, 'updateVehicle']);
        Route::delete('vehicles/{vehicle}', [OperationsController::class, 'deleteVehicle']);
        Route::get('route-plans', [OperationsController::class, 'routes']);
        Route::post('route-plans', [OperationsController::class, 'storeRoute']);
        Route::put('route-plans/{route}', [OperationsController::class, 'updateRoute']);
        Route::delete('route-plans/{route}', [OperationsController::class, 'destroyRoute']);
        Route::get('quotes', [OperationsController::class, 'quotes']);
        Route::post('quotes', [OperationsController::class, 'storeQuote']);
        Route::put('quotes/{quote}', [OperationsController::class, 'updateQuote']);
        Route::post('quotes/{quote}/convert', [OperationsController::class, 'convertQuote']);
        Route::get('notification-templates', [OperationsController::class, 'templates']);
        Route::post('notification-templates', [OperationsController::class, 'storeTemplate']);
        Route::put('notification-templates/{template}', [OperationsController::class, 'updateTemplate']);
        Route::get('audit-logs', [OperationsController::class, 'audit']);
        Route::get('settings', [SettingsController::class, 'show']);
        Route::put('settings', [SettingsController::class, 'update']);
        Route::post('settings', [SettingsController::class, 'update']);
        Route::get('documents', [BusinessDocumentController::class, 'index']);
        Route::post('documents', [BusinessDocumentController::class, 'store']);
        Route::get('documents/{document}', [BusinessDocumentController::class, 'show']);
    });
});

